#!/usr/bin/env ruby

require 'term/ansicolor'
include Term::ANSIColor

readme        = File.read('../readme.md').split(/\n/)
topics        = {}
current_topic = ''

readme.each do |line|
  if line.include? '###'
    current_topic = line.gsub('#','')    
    topics[current_topic] = []
  else
    topics[current_topic] << line if topics[current_topic] unless line.include? 'objective'
  end
end

def test(index,topics)
  topic = topics.keys[index]
  steps = topics.values[index]
  puts "[#{index}] - #{topic}".yellow
  steps.each do |step|
    tick = '`'
    code = step[/#{tick}(.*?)#{tick}/,1]

    if code 
      puts step.gsub(code, code.bright_green).gsub('`','')  
    else
      puts step
    end
  end
end

test 8, topics
test 9, topics
test 10, topics
test 11, topics
test 12, topics
test 13, topics
