#!/usr/bin/env ruby

require 'term/ansicolor'
include Term::ANSIColor

mainpath      = '/Users/jonathan.starr/.learn/lib'

readme        = File.read("#{mainpath}/readme.md").split(/\n/)
topics        = {}
current_topic = ''

readme.each do |line|
  if line.include? '###'
    current_topic = line.gsub('#','')    
    topics[current_topic] = []
  else
    topics[current_topic] << line if topics[current_topic] unless line.include? 'objective'
  end
end

def test(index,topics)
  steps = topics.values[index]
  steps.each do |step|
    tick = '`'
    code = step[/#{tick}(.*?)#{tick}/,1]

    if code 
      puts step.gsub(code, code.bright_green).gsub('`',' ')  
    else
      puts step
    end
  end
end

# main entry point of the test

topic = ARGV.first.to_i
topic ||= 0

while true
  system 'clear'
  header = topics.keys[topic]
  puts "[#{topic}] - #{header}".yellow
  puts ''
  puts "[press any key]".red
  $stdin.gets()
  test(topic, topics)  
  puts "[next topic]".red
  $stdin.gets()
  topic += 1
end
